// <auto-generated />
namespace Final_CapAPi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202001292015174_addModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
